create table users(
    id int primary key generated by default as identity,
    name varchar(100) not null,
    email varchar(100) not null unique,
    age int check (age between 0 and 120) not null,
    created_at timestamp not null
);
